name: React Docker CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker compose
        run: docker compose up deploy 
