name: React Docker CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t react-app .

      # Run container in background
      - name: Run Docker container
        run: docker run -d --name react-container react-app

      # Stop and clean up container
      - name: Stop container
        run: docker stop react-container && docker rm react-container
